name: copybara

on:
  workflow_dispatch:
    inputs:
      pr:
        type: number
        description: The pr to sync
    
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - copy.bara.sky

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  copybara-build:
    name: Build copybara
    runs-on: ubuntu-latest

    steps:

      - name: checkout copybara repo
        uses: actions/checkout@v4
        with:
          repository: google/copybara
          ref: main

      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          architecture: x64
      
      - name: setup bazel
        uses: bazel-contrib/setup-bazel@0.9.1
        with:
          bazelisk-cache: false
          disk-cache: ${{ github.workflow }}
          repository-cache: false

      - name: build copybara using bazel
        run: |
          bazel build //java/com/google/copybara:copybara_deploy.jar

      - name: Upload binary to github
        uses: actions/upload-artifact@v4
        with:
          name: copybara_deploy.jar
          path: bazel-bin/java/com/google/copybara/copybara_deploy.jar

  copybara:
    name: Run copybara sync
    runs-on: ubuntu-latest
    needs: 
      - copybara-build

    steps:

      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: setup java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          architecture: x64

      - name: Git config setup
        shell: bash
        run: |
          git config --global user.name copybara-bot
          git config --global user.email copybara-bot@oqc.tech
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@api.github.com" > ~/.git-credentials

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.PUBLIC_DEPLOY_KEY }}
            ${{ secrets.PRIVATE_DEPLOY_KEY }}

      - name: download copybara
        uses: actions/download-artifact@v4
        with:
          name: copybara_deploy.jar
          path: /usr/local/bin/

      - name: run copybara sync
        if: ${{ github.event_name == 'push' }}
        run: |
          java -jar /usr/local/bin/copybara_deploy.jar copy.bara.sky sync

      - name: run copybara pr
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          java -jar /usr/local/bin/copybara_deploy.jar copy.bara.sky pull ${{ inputs.pr }}
